rm -f "See See.popclipextz"
mkdir "See See.popclipext"
cp Config.plist "See See.popclipext"
cp Pot.png "See See.popclipext"
cp Pot.sh "See See.popclipext"
zip -r "See See.popclipextz" "See See.popclipext"
rm -r "See See.popclipext"
